/**
 * Cloudflare Worker for Gallery Authentication
 * Returns actual image URLs only if password is correct
 */

// GALLERY CONFIGURATION - Generated by generate-worker-config.js
const GALLERY_PASSWORDS = {
};
const GALLERY_IMAGES = {
};

export default {
  async fetch(request, env) {
    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    };

    // Handle CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders });
    }

    if (request.method !== 'POST') {
      return new Response(JSON.stringify({ error: 'Method not allowed' }), {
        status: 405,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    try {
      const { password, galleryPath } = await request.json();

      if (!password || !galleryPath) {
        return new Response(JSON.stringify({ error: 'Password and gallery path required' }), {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }

      // Check if gallery exists
      const galleryPassword = GALLERY_PASSWORDS[galleryPath];

      if (!galleryPassword) {
        return new Response(JSON.stringify({ a: galleryPassword, error: 'Gallery not found' }), {
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }

      if (galleryPassword !== password) {
        return new Response(JSON.stringify({ error: 'Invalid password' }), {
          status: 401,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }

      // Password correct - return image data
      // This data is NOT publicly accessible (only in worker code after deployment)
      const galleryImages = GALLERY_IMAGES[galleryPath];

      if (!galleryImages) {
        return new Response(JSON.stringify({ error: 'No images found for this gallery' }), {
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }

      return new Response(JSON.stringify({
        success: true,
        images: galleryImages
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });

    } catch (error) {
      console.error('Worker error:', error);
      return new Response(JSON.stringify({ error: 'Internal server error' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }
  }
};
